### ISSUE TITLE
fips hungs at the startup

### ISSUE THREAD

**Issue by matwey** [matwey/fips3#83]
Hello, I am running fips from master and see the following at startup when I try to load **float32** image. The application takes 100% CPU, it seems to be stuck here.

My Qt version is 5.9.4, Mesa is 18.0.2

```
0x00007ffff728ae63 in QOpenGLTexture::allocateStorage(QOpenGLTexture::PixelFormat, QOpenGLTexture::PixelType) () from /usr/lib64/libQt5Gui.so.5
(gdb) bt
#0  0x00007ffff728ae63 in QOpenGLTexture::allocateStorage(QOpenGLTexture::PixelFormat, QOpenGLTexture::PixelType) () from /usr/lib64/libQt5Gui.so.5
#1  0x000000000041c8bd in AbstractOpenGLTexture::initialize() ()
#2  0x0000000000429098 in OpenGLWidget::initializeGLObjects() ()
#3  0x00007ffff7762435 in ?? () from /usr/lib64/libQt5Widgets.so.5
#4  0x00007ffff7762a72 in QOpenGLWidget::resizeEvent(QResizeEvent*) () from /usr/lib64/libQt5Widgets.so.5
#5  0x00000000004296e2 in OpenGLWidget::resizeEvent(QResizeEvent*) ()
#6  0x00007ffff7743832 in QWidget::event(QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#7  0x00007ffff7706e8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib64/libQt5Widgets.so.5
#8  0x00007ffff770e244 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#9  0x00007ffff6976a88 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /usr/lib64/libQt5Core.so.5
#10 0x00007ffff773c1fb in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) ()
   from /usr/lib64/libQt5Widgets.so.5
#11 0x00007ffff773fd93 in QWidgetPrivate::show_helper() () from /usr/lib64/libQt5Widgets.so.5
#12 0x00007ffff77428cb in QWidget::setVisible(bool) () from /usr/lib64/libQt5Widgets.so.5
#13 0x00007ffff773fd10 in QWidgetPrivate::showChildren(bool) () from /usr/lib64/libQt5Widgets.so.5
#14 0x00007ffff773fdaf in QWidgetPrivate::show_helper() () from /usr/lib64/libQt5Widgets.so.5
#15 0x00007ffff77428cb in QWidget::setVisible(bool) () from /usr/lib64/libQt5Widgets.so.5
#16 0x00007ffff773fd10 in QWidgetPrivate::showChildren(bool) () from /usr/lib64/libQt5Widgets.so.5
#17 0x00007ffff773fdaf in QWidgetPrivate::show_helper() () from /usr/lib64/libQt5Widgets.so.5
#18 0x00007ffff77428cb in QWidget::setVisible(bool) () from /usr/lib64/libQt5Widgets.so.5
#19 0x0000000000421178 in Instance::Instance(QObject*, QString const&) ()
---Type <return> to continue, or q <return> to quit---
#20 0x000000000041cc7b in Application::Application(int&, char**) ()
#21 0x0000000000421b99 in main ()
```

**Comment by matwey** [comment]
Fixed via #104
